version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - mkdir -p ~/.ssh
      - echo "$build_ssh_key" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - cat ~/.ssh/id_rsa
      - ssh-keygen -F github.com || ssh-keyscan github.com >>~/.ssh/known_hosts
      - git config --global url."git@github.com:".insteadOf "https://github.com/"
      - git init
      - git remote add origin git@github.com:DIS-SIN/Ghost.git
      - git fetch
      - git checkout -t origin/stable
      - git submodule init
      - git submodule update --recursive
      - echo $(ls ./core/client)
      - aws s3 cp s3://ghost-secrets/config.production.json config.production.json
      - yarn global add knex-migrator grunt-cli ember-cli bower
  build:
    commands:
      - "echo $NODE_ENV"
      - "yarn setup"
artifacts:
  files:
    - '**/*'


  