version: 0.2

env:
  variables:
    NODE_ENV: "production"

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - "git init"
      - "git remote add origin https://github.com/DIS-SIN/Ghost.git"
      - "git submodule init"
      - "git submodule update --recursive"
      - "aws s3 cp s3://ghost-secrets/config.production.json config.production.json"
      - "yarn global add knex-migrator grunt-cli ember-cli bower"
  build:
    commands:
      - "yarn setup"
      - "grunt prod"



  