routes:

collections:
  /:
    permalink: /en/{slug}/
    filter: tag:english
    template: index

  /fr/:
    permalink: /fr/{slug}/
    filter: tag:francais
    template: index

  /splash/:
    permalink: /splash/
    template: splash

  /en/about/:
    permalink: /en/about/
    template: About

  /fr/about/:
    permalink: /fr/about/
    template: About-fr

  /en/12-days-of-data/:
    permalink: /en/12-days-of-data/
    template: dataDays

  /fr/12-days-of-data/:
    permalink: /fr/12-days-of-data/
    template: dataDays-fr

  /en/9-days-of-working-remotely/:
    permalink: /en/9-days-of-working-remotely/
    template: remoteWorkDays

  /fr/9-days-of-working-remotely/:
    permalink: /fr/9-days-of-working-remotely/
    template: remoteWorkDays-fr

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/